Support Reason 3 and Next.js 4
ulrikstrid/bs-next pull request #2
Opened 2017-11-26 22:06 UTC by dcalhoun

Convert source to [Reason 3](https://reasonml.github.io/community/blog/#reason-3) and bump version to [Next.js 4](https://zeit.co/blog/next4).

### Additional Changes

The following were done with the primary goal of aligning with ReasonReact repo structure and following the recommendations found in the ReasonML docs.

* Capitalize Reason source files. ([ref](https://reasonml.github.io/guide/meta/project-structure#file-casing))
* Include JS output in version control. ([ref](https://reasonml.github.io/guide/javascript/converting#tips))
* Utilize Yarn for tracking package versions.
* Add documentation and examples.

---

I am _super_ new to ReasonML. So, please double check my conversion. I basically stumbled through the syntax until it began working for my app. 😊

2017-11-28 08:59 UTC, ulrikstrid commented
Hey, I've been sick for a while so have some catching up to do, but I will have a look at this during the day!

Thanks!

2017-11-28 13:22 UTC, ulrikstrid requested changes
Looks good, just one small tweak.

2017-11-28 13:22 UTC, ulrikstrid commented on src/Next.re
> +  let make = (_children) =>
`children` should not be underscored as that indicates that it isn't  used.

2017-11-28 15:16 UTC, dcalhoun commented
@ulrikstrid Thank you for taking the time to review. I've addressed your feedback.

2017-11-29 20:31 UTC, merged

2017-11-29 20:32 UTC, ulrikstrid commented
@dcalhoun thanks a lot for this! 🥇

2017-12-16 08:03 UTC, ulrikstrid commented
This is finally up, sorry for being slow